### ISSUE TITLE
multiple definition of `__exidx_end' when building two audio objects for teensy

### ISSUE THREAD

**Issue by flojawi** [grame-cncm/faust#434] opened 2020-05-03 14:02 UTC
When attempting to compile more than one teensy audio object (created via `faust2teensy -lib`) in the Arduino IDE, i get following compiler error:
```


/tmp/arduino_build_262199/sketch/bandlimitedosci.cpp: In constructor 'bandlimitedosci::bandlimitedosci()':
bandlimitedosci.cpp:5138: warning: operation on '((bandlimitedosci*)this)->bandlimitedosci::fDSP' may be undefined 
 bandlimitedosci::bandlimitedosci() : AudioStream((fDSP = new mydsp())->getNumInputs(), new audio_block_t*[fDSP->getNumInputs()])
                                                                                                                                ^
/tmp/arduino_build_262199/sketch/zita.cpp: In constructor 'zita::zita()':
zita.cpp:5625: warning: operation on '((zita*)this)->zita::fDSP' may be undefined 
 zita::zita() : AudioStream((fDSP = new mydsp())->getNumInputs(), new audio_block_t*[fDSP->getNumInputs()])
                                                                                                          ^
/tmp/arduino_build_262199/sketch/zita.cpp.o:(.bss.__exidx_end+0x0): multiple definition of `__exidx_end'
/tmp/arduino_build_262199/sketch/bandlimitedosci.cpp.o:(.bss.__exidx_end+0x0): first defined here
/usr/share/arduino/hardware/tools/arm/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld: Disabling relaxation: it will not work with multiple definitions
/tmp/arduino_build_262199/sketch/zita.cpp.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::_Alloc_hider(char*, std::allocator<char> const&)':
/usr/share/arduino/hardware/tools/arm/arm-none-eabi/include/c++/5.4.1/cmath:408: multiple definition of `__exidx_start'
/tmp/arduino_build_262199/sketch/bandlimitedosci.cpp.o:/tmp/arduino_build_262199/sketch/bandlimitedosci.cpp:5057: first defined here
collect2: error: ld returned 1 exit status
```
In my example, i included two objects, one called bandlimitedosci and one zita.

**Comment by sletz** [comment] 2020-05-03 16:47
Can you post the 2 C++ compiled file somewhere ?

**Comment by flojawi** [comment] 2020-05-04 10:45
I have created a more minimalist example that recreates the problem. 
I have an .ino file called oscillators
```
#include <Audio.h>
#include "triangle.h"
#include "sawtooth.h" 

void setup() {
}

void loop() {
}
```
then I have a .dsp file called triangle.dsp 
```
import("stdfaust.lib");
process = 200: os.triangle;
```
and one called sawtooth.dsp 
```
import("stdfaust.lib");
process = 200: os.sawtooth;
```

And this is the compiler error in the Arduino IDE: 
```
/tmp/arduino_build_9338/sketch/triangle.cpp: In constructor 'triangle::triangle()':
/tmp/arduino_build_9338/sketch/triangle.cpp:5003:114: warning: operation on '((triangle*)this)->triangle::fDSP' may be undefined [-Wsequence-point]
 triangle::triangle() : AudioStream((fDSP = new mydsp())->getNumInputs(), new audio_block_t*[fDSP->getNumInputs()])
                                                                                                                  ^
/tmp/arduino_build_9338/sketch/sawtooth.cpp: In constructor 'sawtooth::sawtooth()':
/tmp/arduino_build_9338/sketch/sawtooth.cpp:4950:114: warning: operation on '((sawtooth*)this)->sawtooth::fDSP' may be undefined [-Wsequence-point]
 sawtooth::sawtooth() : AudioStream((fDSP = new mydsp())->getNumInputs(), new audio_block_t*[fDSP->getNumInputs()])
                                                                                                                  ^
/tmp/arduino_build_9338/sketch/triangle.cpp.o:(.bss.__exidx_end+0x0): multiple definition of `__exidx_end'
/tmp/arduino_build_9338/sketch/sawtooth.cpp.o:(.bss.__exidx_end+0x0): first defined here
Mehrere Bibliotheken wurden für "SD.h" gefunden
/usr/share/arduino/hardware/tools/arm/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld: Disabling relaxation: it will not work with multiple definitions
 Benutzt: /usr/share/arduino/hardware/teensy/avr/libraries/SD
/tmp/arduino_build_9338/sketch/triangle.cpp.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::_Alloc_hider(char*, std::allocator<char> const&)':
 Nicht benutzt: /usr/share/arduino/libraries/SD
/tmp/arduino_build_9338/sketch/triangle.cpp:280: multiple definition of `__exidx_start'
/tmp/arduino_build_9338/sketch/sawtooth.cpp.o:/tmp/arduino_build_9338/sketch/sawtooth.cpp:285: first defined here
collect2: error: ld returned 1 exit status
```

Attached is a .zip file with the .h and .cpp files

[oscillators.zip](https://github.com/grame-cncm/faust/files/4574127/oscillators.zip)

**Comment by sletz** [comment] 2020-05-04 11:23
I don't see anything clear in the C++ code. This linker issue is a weird one.  I suggest to report and ask on te Teensy forum.

**Comment by sletz** [comment] 2020-05-16 04:33
Reading this https://forum.pjrc.com/threads/55274-Using-Faust-with-Teensy?highlight=faust, it seem the problem is solved. Can we close this issue?

**Closed** 2020-05-17 21:32 UTC
