### ISSUE TITLE
Rust Warning: "creating a mutable reference to mutable static is discouraged", How do we want to deal with this?

### ISSUE THREAD

**Issue by crop2000** [grame-cncm/faust#1092] opened 2024-12-09 12:02 UTC
Currently Buffers are filled with data are global.
The Buffer needs to be mutable for the case of a sample rate change. 
The use-case of Faust expects that the functions that update the content of the buffer are only called when no compute function is running. because of this we didn't experience UB. 
The solution that would prevent any UB would be to use a RWLock to prevent access to the Buffer while it is updated.
The RWLock needs to be checked at every compute block. This has some overhead.
Right now i don't see another Solution.

```
warning: creating a mutable reference to mutable static is discouraged
   --> src/bin/grain3.rs:332:38
    |
332 |         sig1.fillmydspSIG1(65536, unsafe { &mut ftbl1mydspSIG1 });
    |                                            ^^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
    |
    = note: for more information, see issue #114447 <https://github.com/rust-lang/rust/issues/114447>
    = note: this will be a hard error in the 2024 edition
    = note: this mutable reference has lifetime `'static`, but if the static gets accessed (read or written) by any other means, or any other reference is created, then any further use of this mutable reference is Undefined Behavior
help: use `addr_of_mut!` instead to create a raw pointer
    |
332 |         sig1.fillmydspSIG1(65536, unsafe { addr_of_mut!(ftbl1mydspSIG1) });
    |                                            ~~~~~~~~~~~~~              +
```

**Comment by crop2000** [comment] 2024-12-09 12:02
@bluenote10

**Comment by bluenote10** [comment] 2024-12-09 12:09
This is likely a duplicate of https://github.com/grame-cncm/faust/issues/1005. So far I was considering to use something based on `thread_local!`, but I would suggest to keep the discussion in one place.

**Closed** 2024-12-09 13:06 UTC
